title:            Martín González
tagline:          Data journalist and free software
description:      "Data journalist, Github Lurker, Journalism student"
#Comment out url when working locally to resolve base urls correctly
# url: https://martingonzalez.net

# Owner/author information
owner:
  name:           Martín González
  bio:            Journalism student at Pompeu Fabra University
  email:          hi at martingonzalez.net
  twitter:        martgnz        
  github:         martgnz       
  disqus:         martingonzalez
  location:       "Barcelona, ES"

tools:
  standards:      "HTML, SCSS, Jekyll and awesomeness"
  software:       "git"

# Links to include in top navigation
# For external links add external: true

links:
  - title: Portfolio
    url: "/#portfolio"
  - title: Blog
    url: /blog
  - title: About me
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Madrid
future:      true
highlighter:    pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]

# Cool pagination
paginate: 5
paginate_path: "/blog/page/:num"

# gems fun
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap

# twitter mentions
jekyll-mentions: https://twitter.com